namespace: citizennone
name: rkhunter
version: 1.0.0
src: citizennone/rkhunter
readme: README.md
authors:
  - Marcin Dołęgowski <marcin.dolegowski@debian.org.pl>
description: >
  Lightweight Ansible role for installing and configuring Rootkit Hunter (rkhunter) on Debian and RedHat-based systems.
  Includes logrotate integration, optional support for additional utils, and basic configuration tweaks.
license: MIT
min_ansible_version: "2.9"
platforms:
  - name: Debian
    versions:
      - bookworm
      - bullseye
      - buster
  - name: RedHat
    versions:
      - 8
      - 9
  - name: Fedora
    versions:
      - all
tags:
  - rkhunter
  - security
  - monitoring
  - rootkit
  - hardening
  - linux
dependencies: []
