- name: Install RKHunter related tools
  ansible.builtin.include_tasks: rkhunter-utils.yml
  when: rkhunter_enabled | default(false) and rkhunter_install_utils | default(false)

- name: Enable rkhunter for Debian
  ansible.builtin.include_tasks: rkhunter-debian.yml
  when: rkhunter_enabled | default(false) and ansible_os_family == "Debian"

- name: Enable rkhunter for Redhat
  ansible.builtin.include_tasks: rkhunter-redhat.yml
  when: rkhunter_enabled | default(false) and (ansible_os_family == "RedHat" or ansible_distribution == "Fedora")
