---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-debian
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true
    tty: true
  - name: instance-centos
    image: quay.io/centos/centos:stream9
    privileged: true
    tty: true
    ansible_python_interpreter: /usr/libexec/platform-python
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
verifier:
  name: ansible
