---
- name: Prepare container for Ansible
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Always create remote tmp dir
      ansible.builtin.raw: mkdir -p /tmp/.ansible/tmp || true
      changed_when: false

    - name: Gather facts manually
      ansible.builtin.setup:

    - name: Install python3-dnf package (RedHat)
      ansible.builtin.raw: dnf install -y python3-dnf
      when: ansible_facts['os_family'] == 'RedHat'
      changed_when: false
